

import { Metadata } from 'next';
import React from 'react'

type SingleProductlayoutProps={
    children:React.ReactNode
}

export const metadata: Metadata = {
    title: "Shoping",
    description: "Generated by create next app",
  };

const SingleProductlayout = ({children}:SingleProductlayoutProps) => {
  return (
    <div>
        {children}
    </div>
  )
}

export default SingleProductlayout